services:
  - type: web
    name: careerlens-api
    runtime: python-3.11
    rootDir: careerlens-backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: 1
      - key: RENDER_PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        value: "libsql://careerlens-raomitesh21.aws-eu-west-1.turso.io?authToken=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzQ0NDg4MjIsImlkIjoiMDE5ZDI1NWY-YWEwMS03NzU0LWEyMzEtNTE2NjIzMTMwMTRkIiwicmlkIjoiZjUwZjllZmMtMjY1ZS00NzE5LTk4MjItYTk2MzljNzQ5OThkIn0.ZsUXkcBqgmYiY6H-W713GYwG8dXMSAiz7XJVkREiC7T5ssvS_WqXwPiJfVB7hDUrIvlfpWNgX2TgOw1pjbl_DA"
